version: '3.7'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - php
      - mysql



  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3004:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE : realestate
       MYSQL_USER : root
       MYSQL_PASSWORD : root
       MYSQL_ROOT_PASSWORD : root
       SERVICE_TAG : dev
       SERVICE_NAME : mysql
    networks:
      - laravel



  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
